# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: 김동규
title: Java 주니어 개발자
email: mr_dongkyu@naver.com
# website: www.github.com/dongkyu92
phone: 010-9197-7392

# Social links
# twitter_username: facespics
github_username:  dongkyu92
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/프로필사진.jpg
about_content: | # this will include new lines to allow paragraphs
  

  안녕하세요. 백엔드 개발자를 희망하는 <mark>김동규</mark>입니다.
    
    <br>
    즐겁게 근무할 수 있는 회사와 동료가 있는 환경에서 성장하고 싶습니다. <br>
    현재 Spring Boot로 만들 개인 프로젝트를 기획하고 있습니다.
    

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
