# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: 김동규
title: Java 주니어 개발자
email: mr_dongkyu@naver.com
# website: www.github.com/dongkyu92
phone: 010-9197-7392

# Social links
# twitter_username: facespics
github_username:  dongkyu92
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/프로필사진.jpg
about_content: | # this will include new lines to allow paragraphs
  

  Java & Spring 기반 백엔드 개발자를 희망하는 <mark>김동규</mark> 입니다.
  서로 긍정적인 <mark>피드백</mark>을 주는 동료가 있는 회사에서 <mark>성장</mark>하고 싶습니다.
  <br>
  저는 새로운 언어와 기술을 배우는 것을 즐기고 러닝 커브가 높습니다.
  프로젝트를 진행하면서 기획에서 개발, 배포까지 경험해보았습니다.
  그 개발 기간 동안 항상 어떠한 코드가 더 좋은지 고민했으며,
  필요하다면 새로운 언어와 기술을 배우는 것을 마다하지 않고 러닝 커브가 높습니다.
  <br>

  현재 Spring Boot와 React 템플릿 엔진, Spring Security를 사용한 개인 토이 프로젝트를 기획 중입니다.
    

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
