# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 김동규
title: Java 주니어 개발자
email: mr_dongkyu@naver.com
# email_title: Email (Email title override)
phone: 010-9197-7392
# phone_title: Phone (Phone title override)


# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: jekyllrb
github_username:  dongkyu92
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/프로필사진.jpg
about_content: | # this will include new lines to allow paragraphs
  Java & Spring 기반 백엔드 개발자를 희망하는 <mark>김동규</mark> 입니다.<br>
  서로 긍정적인 <mark>피드백</mark>을 주는 동료가 있는 회사에서 <mark>성장</mark>하고 싶습니다.<br>
  <br>
  저는 새로운 언어와 기술을 배우는 것을 즐기고 러닝 커브가 높습니다.<br>
  프로젝트를 진행하면서 <mark>기획</mark>에서 <mark>개발</mark>, <mark>배포</mark>까지 경험해보았습니다.<br>
  개발 기간 동안 항상 <mark>효율적인 코드</mark> 작성에 힘 썼으며,<br>
  <mark>코드리뷰</mark> 또한 중요하게 생각합니다.<br>
  <br>

  현재 Spring Boot와 React 템플릿 엔진, Spring Security를 사용한 개인 토이 프로젝트를 기획 중입니다.

content:
  - title: Skill
    layout: list
    content:
      - layout: left
        title: PL / IDE
        description: | # this will include new lines to allow paragraphs
          * <mark>Java</mark>, JavaScript, C, C++, C#
          * HTML, CSS
          * R, Python
          * IntelliJ, Eclipse, Visual Studio Code, Visual Studio

      - layout: left
        title: Framework / Library
        description: | # this will include new lines to allow paragraphs
          * <mark>Spring MVC</mark>, Spring Security
          * JQuery, Bootstrap
          * KoNLP
          * D3.js
          * Django

      - layout: left
        title: Server
        description: | # this will include new lines to allow paragraphs
          * <mark>Oracle</mark>
          * MySQL
          * Tomcat

      - layout: left
        title: Tooling / DevOps
        description: | # this will include new lines to allow paragraphs
          * <mark>AWS RDS, EC2</mark>
          * Docker container
          * Github, Tomcat, maven, bash

      - layout: left
        title: Environment
        description: | # this will include new lines to allow paragraphs
          * <mark>MacOS</mark>
          * linux
          * AWS
          * Windows
    

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 음식 추천서비스
        sub_title: Django 기반 웹 서비스
        caption: 팀장 / 3명<br>백엔드 개발 및 지도 서비스 구현 담당<br>2020.06.22 ~ 2020.07.06
        additional_links:
          - title:  dongkyu92/Foother
            icon: fab fa-github
            url: https://github.com/dongkyu92/Foother-multicampus
        description: | # this will include new lines to allow paragraphs
          * 프로젝트 개요 및 기능
            - 사용자 위치 기반 음식점 검색 기능
            - 사용자 간 음식 게시물(위치, 사진, 시간, 평점) 공유
            - 랜덤 음식 추천 기능
          * Web Backend
            - Python, Django, SQLite, Kakao API, axios
          * Web Frontend
            - HTML5, CSS3, JS ES6, Bootstrap
          * Versioning: Git 협업 플로우<br>
          <br>
          <br>
          <br>

      - layout: left
        title: 58세대를 위한 건강 정보 서비스
        sub_title: Spring MVC 기반 웹 서비스
        caption: 팀장 / 4명<br>백엔드 개발 및 회원 시스템 담당<br>2020.05.09 ~ 2020.06.04
        link: http://www.58opal.shop:8000/opalproject
        link_text: http://www.58opal.shop:8000/opalproject
        additional_links:
          - title:  dongkyu92/opalproject
            icon: fab fa-github
            url: https://github.com/dongkyu92/opalproject
        quote: >
          <mark>멀티캠퍼스 실무 프로젝트 우수상 & 농림 축산 식품부 창업 공모전 본선 진출</mark>
        description: | # this will include new lines to allow paragraphs
          * 프로젝트 개요 및 기능
            - 58세대를 위한 건강정보 제공
            - 다빈도 질병과 해당 질병에 좋은 식품을 영양 성분별 구성
            - 뉴스 기사 크롤링, 보건 의료 빅데이터, 농림축산식품부 빅데이터를 활용하여 d3.js로 시각화
            - 식품별, 농가별 식품 판매 페이지 구성 & 장바구니 & 가결제 기능 구현
          * Web Backend
            - Java, Spring MVC, Spring Security, Oracle
          * Web Frontend
            - HTML5, CSS3, JS ES6, D3.js, Bootstrap, JQuery
          * Versioning: Git 협업 플로우<br>

      - layout: right
        description: | # this will include new lines to allow paragraphs
          ![프로젝트 우수상](/images/우수상.jpeg) ![공모전 본선 진출](/images/공모전.png)
          <br>
          <br>
          <br>
          <br>
          <br>

      - layout: left
        title: 골목 상권 분석 서비스
        sub_title: Spring MVC 기반 웹 서비스
        caption: 팀장 / 3명<br>백엔드 개발 및 컨설팅 페이지 담당<br>2020.03.09 ~ 2020.03.21
        additional_links:
          - title:  dongkyu92/backstreet
            icon: fab fa-github
            url: https://github.com/dongkyu92/backstreet
        description: | # this will include new lines to allow paragraphs
          * 프로젝트 개요 및 기능
            - 예비 창업자를 위한 골목 상권 분석 서비스
            - 서울시 공공데이터, KT BigSight 이용 데이터 확보
          * Web Backend
            - Java, Spring MVC, Oracle, Kakao API
          * Web Frontend
            - HTML5, CSS3, JS ES6, Bootstrap, JQuery
          <br>
          <br>

      - layout: left
        title: 게시판 제작<br>(토이 프로젝트)
        sub_title: Spring MVC 기반 웹 서비스
        caption: 개인 / 2020.02
        description: | # this will include new lines to allow paragraphs
          * CURD 기능 구현
          * 페이징 기능 구현
          <br>


  - title: Education & Career
    layout: list
    content:
      - layout: top-left
        title: 공공데이터 청년인턴
        sub_title: 효성ITX
        caption: 2020.09 - 2020.12
        description: | # this will include new lines to allow paragraphs
          * 개방 전 인허가 데이터를 정비하는 업무를 했습니다.
            - 광고 및 간판업, 축산업, 의료데이터 등
          * API로 사용될 데이터를 하나씩 점검하여 업무 담당자에게 전송했습니다.
          * 실측 업무를 통해 보안등의 위치 정보를 점검하고 오류가 있는 데이터를 정정했습니다.
          <br>
          <br>
          <br>
      - layout: top-left
        title: OpenAPI를 활용한 빅데이터 전처리ㆍ시각화
        sub_title: 삼성 멀티캠퍼스 역삼
        caption: 2019.11 - 2020.07
        description: | # this will include new lines to allow paragraphs
          * Java(jdk 1.8) 기본 문법부터 File I/O, Collection FrameWork, Thread 등을 학습했습니다.
          * HTML, CSS와 Javascript로 웹 사이트의 레이아웃을 교육 받았고, 반응형 웹, 돔 객체를 활용해 동적인 웹 사이트 구현을 실습했습니다. 
          * 서블릿을 공부했고 EL, JSTL을 활용한 JSP 페이지 구성방법을 학습했습니다.
          * Spring MVC의 구조와 기능에 대해 공부했고, 게시판 제작 미니 프로젝트를 진행했습니다.
          * R을 이용하여 데이터를 수집하는 방법과 정규표현식을 이용해 전처리를 하고 시각화하는 교육을 받았습니다.
          * Django기반 웹 사이트 구축을 교육받고, 팀 프로젝트를 진행했습니다.
          * 실무 프로젝트 우수상을 받고, 농림 축산 식품부 본선에 진출했습니다.
          <br>
          <br>
          <br>

      - layout: top-left
        title: KISA 핀테크X블록체인 아카데미
        sub_title: KISA 핀테크 기술지원센터
        caption: 2018.10.29 - 2018.11.15
        description: | # this will include new lines to allow paragraphs
          * 은행권 공동 OpenAPI를 사용하여 실습 위주로 교육받았습니다.
          * 이더리움 가상화폐 테스트 코인을 채굴했습니다.
          * 실습 내용을 기반으로 팀을 이뤄 프로젝트를 진행했습니다.(은행권 공동 OpenAPI 이용)
          <br>
          <br>
          <br>

      - layout: top-left
        title: 군 복무
        sub_title: 제 65보병사단, 제3야전군사령부
        caption: 2016.03.01 - 2018.06.30
        description: | # this will include new lines to allow paragraphs
          * 정보통신 병과 육군 소위로 임관하여 중위로 제대했습니다.
          * 제65보병사단 (2016.06 - 2017.11)
          * 제3야전군사령부 (2017.12 - 2018.06)
          <br>
          <br>
          <br>

      - layout: top-left
        title: 홍익대학교 컴퓨터공학과
        sub_title: 서울 마포구 와우산로 94
        caption: 2012.03 - 2016.02
        description: | # this will include new lines to allow paragraphs
          * 프로그래밍의 기초를 학습했습니다.
          * C와 C++ 기반 객체지향 프로그래밍과 자료구조, 알고리즘을 학습했습니다.
          * Unity 3D를 활용한 게임 제작과 OpenGL을 활용한 프로젝트에 참여했습니다.
          * PL의 역사와 CPU등 하드웨어의 구조와 기능을 학습했습니다.
          * 운영체제에 대해 학습했습니다.
          * Network의 이론과 원리를 학습했습니다.
          * 소프트웨어 공학을 학습하며 다양한 프로그래밍 개발론을 학습했습니다.

          
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
